<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.GDnh_k8' shared service.

return $this->privates['.service_locator.GDnh_k8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\HomeController::postImageAction' => ['privates', '.service_locator.gjcjVxG', 'get_ServiceLocator_GjcjVxGService.php', true],
    'App\\Controller\\HomeController::postListAction' => ['privates', '.service_locator.gjcjVxG', 'get_ServiceLocator_GjcjVxGService.php', true],
    'App\\Controller\\HomeController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\HomeController:postImageAction' => ['privates', '.service_locator.gjcjVxG', 'get_ServiceLocator_GjcjVxGService.php', true],
    'App\\Controller\\HomeController:postListAction' => ['privates', '.service_locator.gjcjVxG', 'get_ServiceLocator_GjcjVxGService.php', true],
    'App\\Controller\\HomeController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
], [
    'App\\Controller\\HomeController::postImageAction' => '?',
    'App\\Controller\\HomeController::postListAction' => '?',
    'App\\Controller\\HomeController::setViewHandler' => '?',
    'App\\Controller\\HomeController:postImageAction' => '?',
    'App\\Controller\\HomeController:postListAction' => '?',
    'App\\Controller\\HomeController:setViewHandler' => '?',
]);
