<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.gjcjVxG' shared service.

return $this->privates['.service_locator.gjcjVxG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'fetcher' => ['privates', '.errored..service_locator.gjcjVxG.FOS\\RestBundle\\Request\\ParamFetcher', NULL, 'Cannot autowire service ".service_locator.gjcjVxG": it references class "FOS\\RestBundle\\Request\\ParamFetcher" but no such service exists. Try changing the type-hint to "FOS\\RestBundle\\Request\\ParamFetcherInterface" instead.'],
], [
    'fetcher' => 'FOS\\RestBundle\\Request\\ParamFetcher',
]);
