<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLPqgx9m\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLPqgx9m/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLPqgx9m.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLPqgx9m\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLPqgx9m\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LPqgx9m',
    'container.build_id' => '739c3d47',
    'container.build_time' => 1566287694,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLPqgx9m');
