<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPS7aYlE\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPS7aYlE/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPS7aYlE.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPS7aYlE\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPS7aYlE\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PS7aYlE',
    'container.build_id' => '52754583',
    'container.build_time' => 1566303705,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPS7aYlE');
