<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'get_lists' => [[], ['_controller' => 'App\\Controller\\HomeController::getListsAction', '_format' => 'json'], [], [['text', '/lists']], [], []],
    'post_list' => [[], ['_controller' => 'App\\Controller\\HomeController::postListAction', '_format' => 'json'], [], [['text', '/lists']], [], []],
    'post_image' => [[], ['_controller' => 'App\\Controller\\HomeController::postImageAction', '_format' => 'json'], [], [['text', '/images']], [], []],
];
